[control_plane]
node0 ansible_host=13.61.154.144 private_ip=10.0.1.169

[workers]
node1 ansible_host=13.48.67.129 private_ip=10.0.1.233
node2 ansible_host=56.228.18.80 private_ip=10.0.1.126

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/capstone-phoenix-key.pem
